{"name":"Wordpress application authentication","id":"wordpress-application-automation;wordpress-application-authentication","testSteps":[{"number":1,"description":"Given that Brandon wants to enter the Wordpress application","duration":2670,"startTime":"2020-01-08T17:28:06.926-05:00[America/Bogota]","exception":{"errorType":"net.thucydides.core.webdriver.DriverConfigurationError","message":"Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at \u0027D:/Proyectos_Intellij_Android/co.com.choucair.automation.android/src/test/resources/app/wordpress.apk\u0027 does not exist or is not accessible\nBuild info: version: \u00273.141.59\u0027, revision: \u0027e82be7d358\u0027, time: \u00272018-11-14T08:17:03\u0027\nSystem info: host: \u0027CHMEPPF0I6LTM\u0027, ip: \u0027172.17.27.139\u0027, os.name: \u0027Windows 10\u0027, os.arch: \u0027amd64\u0027, os.version: \u002710.0\u0027, java.version: \u00271.8.0_231\u0027\nDriver info: driver.version: RemoteDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at \u0027D:/Proyectos_Intellij_Android/co.com.choucair.automation.android/src/test/resources/app/wordpress.apk\u0027 does not exist or is not accessible\n    at getResponseForW3CError (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:388:37)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\nBuild info: version: \u00273.141.59\u0027, revision: \u0027e82be7d358\u0027, time: \u00272018-11-14T08:17:03\u0027\nSystem info: host: \u0027CHMEPPF0I6LTM\u0027, ip: \u0027172.17.27.139\u0027, os.name: \u0027Windows 10\u0027, os.arch: \u0027amd64\u0027, os.version: \u002710.0\u0027, java.version: \u00271.8.0_231\u0027\nDriver info: driver.version: RemoteDriver). See below for more details.","stackTrace":[{"declaringClass":"co.com.choucair.automation.android.stepdefinitions.AuthenticationStepDefinitions","methodName":"thatBrandonWantsToEnterTheWordpressApplication","fileName":"AuthenticationStepDefinitions.java","lineNumber":12},{"declaringClass":"cucumber.runner.Runner","methodName":"runPickle","fileName":"Runner.java","lineNumber":80}]},"result":"ERROR","precondition":false,"level":0},{"number":2,"description":"When I login with the username \"pruebaappappium@gmail.com\" and the password \"pruebaapp99\"","duration":19,"startTime":"2020-01-08T17:28:09.604-05:00[America/Bogota]","result":"SKIPPED","precondition":false,"level":0},{"number":3,"description":"Then you should see the login in the application with the message Logged in as","duration":7,"startTime":"2020-01-08T17:28:09.627-05:00[America/Bogota]","result":"SKIPPED","precondition":false,"level":0}],"userStory":{"id":"wordpress-application-automation","storyName":"Wordpress application automation","path":"src/test/resources/features/wordpress.feature","narrative":"  I, as a user, want to authenticate in the application to verify my credentials","type":"feature"},"featureTag":{"name":"Features/Wordpress application automation","type":"feature","displayName":"Features/Wordpress application automation"},"title":"Wordpress application authentication","tags":[{"name":"Wordpress application automation","type":"feature","displayName":"Wordpress application automation"}],"startTime":"2020-01-08T17:28:06.644-05:00[America/Bogota]","duration":2998,"testFailureCause":{"errorType":"net.thucydides.core.webdriver.DriverConfigurationError","message":"Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at \u0027D:/Proyectos_Intellij_Android/co.com.choucair.automation.android/src/test/resources/app/wordpress.apk\u0027 does not exist or is not accessible\nBuild info: version: \u00273.141.59\u0027, revision: \u0027e82be7d358\u0027, time: \u00272018-11-14T08:17:03\u0027\nSystem info: host: \u0027CHMEPPF0I6LTM\u0027, ip: \u0027172.17.27.139\u0027, os.name: \u0027Windows 10\u0027, os.arch: \u0027amd64\u0027, os.version: \u002710.0\u0027, java.version: \u00271.8.0_231\u0027\nDriver info: driver.version: RemoteDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at \u0027D:/Proyectos_Intellij_Android/co.com.choucair.automation.android/src/test/resources/app/wordpress.apk\u0027 does not exist or is not accessible\n    at getResponseForW3CError (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:388:37)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\nBuild info: version: \u00273.141.59\u0027, revision: \u0027e82be7d358\u0027, time: \u00272018-11-14T08:17:03\u0027\nSystem info: host: \u0027CHMEPPF0I6LTM\u0027, ip: \u0027172.17.27.139\u0027, os.name: \u0027Windows 10\u0027, os.arch: \u0027amd64\u0027, os.version: \u002710.0\u0027, java.version: \u00271.8.0_231\u0027\nDriver info: driver.version: RemoteDriver). See below for more details.","stackTrace":[{"declaringClass":"co.com.choucair.automation.android.stepdefinitions.AuthenticationStepDefinitions","methodName":"thatBrandonWantsToEnterTheWordpressApplication","fileName":"AuthenticationStepDefinitions.java","lineNumber":12},{"declaringClass":"cucumber.runner.Runner","methodName":"runPickle","fileName":"Runner.java","lineNumber":80}]},"testFailureClassname":"net.thucydides.core.webdriver.DriverConfigurationError","testFailureMessage":"Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at \u0027D:/Proyectos_Intellij_Android/co.com.choucair.automation.android/src/test/resources/app/wordpress.apk\u0027 does not exist or is not accessible\nBuild info: version: \u00273.141.59\u0027, revision: \u0027e82be7d358\u0027, time: \u00272018-11-14T08:17:03\u0027\nSystem info: host: \u0027CHMEPPF0I6LTM\u0027, ip: \u0027172.17.27.139\u0027, os.name: \u0027Windows 10\u0027, os.arch: \u0027amd64\u0027, os.version: \u002710.0\u0027, java.version: \u00271.8.0_231\u0027\nDriver info: driver.version: RemoteDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at \u0027D:/Proyectos_Intellij_Android/co.com.choucair.automation.android/src/test/resources/app/wordpress.apk\u0027 does not exist or is not accessible\n    at getResponseForW3CError (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:388:37)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\nBuild info: version: \u00273.141.59\u0027, revision: \u0027e82be7d358\u0027, time: \u00272018-11-14T08:17:03\u0027\nSystem info: host: \u0027CHMEPPF0I6LTM\u0027, ip: \u0027172.17.27.139\u0027, os.name: \u0027Windows 10\u0027, os.arch: \u0027amd64\u0027, os.version: \u002710.0\u0027, java.version: \u00271.8.0_231\u0027\nDriver info: driver.version: RemoteDriver). See below for more details.","testFailureSummary":"ERROR;net.thucydides.core.webdriver.DriverConfigurationError;Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at \u0027D:/Proyectos_Intellij_Android/co.com.choucair.automation.android/src/test/resources/app/wordpress.apk\u0027 does not exist or is not accessible\nBuild info: version: \u00273.141.59\u0027, revision: \u0027e82be7d358\u0027, time: \u00272018-11-14T08:17:03\u0027\nSystem info: host: \u0027CHMEPPF0I6LTM\u0027, ip: \u0027172.17.27.139\u0027, os.name: \u0027Windows 10\u0027, os.arch: \u0027amd64\u0027, os.version: \u002710.0\u0027, java.version: \u00271.8.0_231\u0027\nDriver info: driver.version: RemoteDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at \u0027D:/Proyectos_Intellij_Android/co.com.choucair.automation.android/src/test/resources/app/wordpress.apk\u0027 does not exist or is not accessible\n    at getResponseForW3CError (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:388:37)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\nBuild info: version: \u00273.141.59\u0027, revision: \u0027e82be7d358\u0027, time: \u00272018-11-14T08:17:03\u0027\nSystem info: host: \u0027CHMEPPF0I6LTM\u0027, ip: \u0027172.17.27.139\u0027, os.name: \u0027Windows 10\u0027, os.arch: \u0027amd64\u0027, os.version: \u002710.0\u0027, java.version: \u00271.8.0_231\u0027\nDriver info: driver.version: RemoteDriver). See below for more details.;AuthenticationStepDefinitions.java","projectKey":"","annotatedResult":"ERROR","isManualTestingUpToDate":false,"manual":false,"testSource":"Cucumber","actors":[{"name":"Brandon"}],"result":"ERROR"}